version: '3.4'

services:
    nginx:
        image: nginx:certbot
        network_mode: "host"
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - "~/nginx/www:/usr/share/nginx/html"
            - "~/nginx/logs:/var/log/nginx"
            - "~/nginx/config:/etc/nginx"
            - "~/nginx/certbot/conf:/etc/letsencrypt"
            - "~/nginx/certbot/www:/var/www/certbot"
        container_name: "nginx"
